version: '3'
services:
  container:
    image: opentosca/container:latest
    ports:
      - '1337:1337'
      - '1883:1883' # MQTT
      - '8081-8087:8081-8087'
    environment:
      CONTAINER_HOSTNAME: ${PUBLIC_HOSTNAME_SLAVE_1}
      ENGINE_IA_HOSTNAME: engine-ia-jdk8
      ENGINE_IA_PORT: 8080
      CONTAINER_REPOSITORY_HOSTNAME: container-repository
      CONTAINER_REPOSITORY_PORT: 8080
      ENGINE_PLAN_BPEL_HOSTNAME: engine-plan-bpel
      ENGINE_PLAN_BPMN_PORT: 8080
      CONTAINER_DEPLOYMENT_TESTS: 'false'
      COLLABORATION_MODE: 'true'
      COLLABORATION_HOSTNAMES: '${PUBLIC_HOSTNAME_MASTER}'
      COLLABORATION_PORTS: '1883'
    networks:
      - opentosca
  container-repository:
    image: opentosca/winery:latest
    environment:
      WINERY_PORT: 8091
      WORKFLOWMODELER_PORT: 8091
      TOPOLOGYMODELER_PORT: 8091
      WINERY_HOSTNAME: ${PUBLIC_HOSTNAME_SLAVE_1}
      WORKFLOWMODELER_HOSTNAME: ${PUBLIC_HOSTNAME_SLAVE_1}
      TOPOLOGYMODELER_HOSTNAME: ${PUBLIC_HOSTNAME_SLAVE_1}
      CONTAINER_HOSTNAME: ${PUBLIC_HOSTNAME_SLAVE_1}
    ports:
      - '8091:8080'
    networks:
      - opentosca
  ui:
    image: opentosca/ui:latest
    ports:
      - '8088:8080'
    networks:
      - opentosca
  engine-plan-bpel:
    image: opentosca/ode:latest
    ports:
      - '9763:9763' # http
    networks:
      - opentosca
  engine-ia-jdk8:
    image: opentosca/engine-ia:latest
    ports:
      - '8090:8080'
    networks:
      - opentosca
  winery:
    image: opentosca/winery:latest
    environment:
      WINERY_HOSTNAME: ${PUBLIC_HOSTNAME_SLAVE_1}
      WORKFLOWMODELER_HOSTNAME: ${PUBLIC_HOSTNAME_SLAVE_1}
      TOPOLOGYMODELER_HOSTNAME: ${PUBLIC_HOSTNAME_SLAVE_1}
      CONTAINER_HOSTNAME: ${PUBLIC_HOSTNAME_SLAVE_1}
    ports:
      - '8080:8080'
    networks:
      - opentosca
  dind:
    image: docker:20.10-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    networks:
      - opentosca
    ports:
      - '2222:2375'
      - '9990-9999:9990-9999'
      - '9990-9999:9990-9999/udp'
  proxy:
    build: ../proxy
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
    networks:
      - opentosca
networks:
  opentosca:
    driver: bridge